/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:57:52 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the example table. 
 * You can customize the behavior of this class by editing the class, {@link Example()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractExample 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the simple column2 property. */
    private java.util.Date column2;

    /** The value of the simple column3 property. */
    private java.lang.Double column3;

    /** The value of the simple column4 property. */
    private java.lang.String column4;

    /** The value of the simple column5 property. */
    private java.lang.Integer column5;

    /** The value of the simple column6 property. */
    private java.lang.String column6;

    /** The value of the simple isDeleted property. */
    private java.lang.String isDeleted;

    /**
     * Simple constructor of AbstractExample instances.
     */
    public AbstractExample()
    {
    }

    /**
     * Constructor of AbstractExample instances given a simple primary key.
     * @param id
     */
    public AbstractExample(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the column_2 column.
     * @return java.util.Date
     */
    public java.util.Date getColumn2()
    {
        return this.column2;
    }

    /**
     * Set the value of the column_2 column.
     * @param column2
     */
    public void setColumn2(java.util.Date column2)
    {
        this.column2 = column2;
    }

    /**
     * Return the value of the column_3 column.
     * @return java.lang.Double
     */
    public java.lang.Double getColumn3()
    {
        return this.column3;
    }

    /**
     * Set the value of the column_3 column.
     * @param column3
     */
    public void setColumn3(java.lang.Double column3)
    {
        this.column3 = column3;
    }

    /**
     * Return the value of the column_4 column.
     * @return java.lang.String
     */
    public java.lang.String getColumn4()
    {
        return this.column4;
    }

    /**
     * Set the value of the column_4 column.
     * @param column4
     */
    public void setColumn4(java.lang.String column4)
    {
        this.column4 = column4;
    }

    /**
     * Return the value of the column_5 column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getColumn5()
    {
        return this.column5;
    }

    /**
     * Set the value of the column_5 column.
     * @param column5
     */
    public void setColumn5(java.lang.Integer column5)
    {
        this.column5 = column5;
    }

    /**
     * Return the value of the column_6 column.
     * @return java.lang.String
     */
    public java.lang.String getColumn6()
    {
        return this.column6;
    }

    /**
     * Set the value of the column_6 column.
     * @param column6
     */
    public void setColumn6(java.lang.String column6)
    {
        this.column6 = column6;
    }

    /**
     * Return the value of the is_deleted column.
     * @return java.lang.String
     */
    public java.lang.String getIsDeleted()
    {
        return this.isDeleted;
    }

    /**
     * Set the value of the is_deleted column.
     * @param isDeleted
     */
    public void setIsDeleted(java.lang.String isDeleted)
    {
        this.isDeleted = isDeleted;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Example))
            return false;
        Example that = (Example) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
