/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:58:35 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the problems table. 
 * You can customize the behavior of this class by editing the class, {@link Problems()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractProblems 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the projects association. */
    private Long projectId;

    /** The value of the users association. */
    private Long submitById;

    /** The value of the users1 association. */
    private Long solveById;

    /** The value of the users2 association. */
    private Long validateById;

    /** The value of the simple submitDate property. */
    private java.util.Date submitDate;

    /** The value of the simple problemLevel property. */
    private java.lang.String problemLevel;
    
    private String problemDescription;

    /** The value of the simple correctMeasure property. */
    private java.lang.String correctMeasure;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple closeDate property. */
    private java.util.Date closeDate;

    /**
     * Simple constructor of AbstractProblems instances.
     */
    public AbstractProblems()
    {
    }

    /**
     * Constructor of AbstractProblems instances given a simple primary key.
     * @param id
     */
    public AbstractProblems(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    

    /**
     * Return the value of the submit_date column.
     * @return java.util.Date
     */
    public java.util.Date getSubmitDate()
    {
        return this.submitDate;
    }

    /**
     * Set the value of the submit_date column.
     * @param submitDate
     */
    public void setSubmitDate(java.util.Date submitDate)
    {
        this.submitDate = submitDate;
    }

    /**
     * Return the value of the problem_level column.
     * @return java.lang.Integer
     */
    public java.lang.String getProblemLevel()
    {
        return this.problemLevel;
    }

    /**
     * Set the value of the problem_level column.
     * @param problemLevel
     */
    public void setProblemLevel(java.lang.String problemLevel)
    {
        this.problemLevel = problemLevel;
    }

    /**
     * Return the value of the correct_measure column.
     * @return java.lang.String
     */
    public java.lang.String getCorrectMeasure()
    {
        return this.correctMeasure;
    }

    /**
     * Set the value of the correct_measure column.
     * @param correctMeasure
     */
    public void setCorrectMeasure(java.lang.String correctMeasure)
    {
        this.correctMeasure = correctMeasure;
    }

   
    public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	public Long getSolveById() {
		return solveById;
	}

	public void setSolveById(Long solveById) {
		this.solveById = solveById;
	}

	public Long getSubmitById() {
		return submitById;
	}

	public void setSubmitById(Long submitById) {
		this.submitById = submitById;
	}

	public Long getValidateById() {
		return validateById;
	}

	public void setValidateById(Long validateById) {
		this.validateById = validateById;
	}

	/**
     * Return the value of the status column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the status column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the close_date column.
     * @return java.util.Date
     */
    public java.util.Date getCloseDate()
    {
        return this.closeDate;
    }

    /**
     * Set the value of the close_date column.
     * @param closeDate
     */
    public void setCloseDate(java.util.Date closeDate)
    {
        this.closeDate = closeDate;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Problems))
            return false;
        Problems that = (Problems) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public String getProblemDescription() {
		return problemDescription;
	}

	public void setProblemDescription(String problemDescription) {
		this.problemDescription = problemDescription;
	}
}
