/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:58:51 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the project_reports table. 
 * You can customize the behavior of this class by editing the class, {@link ProjectReports()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractProjectReports 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the projects association. */
    private Long projectId;

    /** The value of the simple reportDate property. */
    private java.util.Date reportDate;

    /** The value of the simple reportName property. */
    private java.lang.String reportName;

    /** The value of the simple excuteStatus property. */
    private java.lang.String excuteStatus;

    /** The value of the simple problem property. */
    private java.lang.String problem;

    /** The value of the simple risk property. */
    private java.lang.String risk;

    /** The value of the simple nextPlan property. */
    private java.lang.String nextPlan;

    /**
     * Simple constructor of AbstractProjectReports instances.
     */
    public AbstractProjectReports()
    {
    }

    /**
     * Constructor of AbstractProjectReports instances given a simple primary key.
     * @param id
     */
    public AbstractProjectReports(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

   
    public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	/**
     * Return the value of the report_date column.
     * @return java.util.Date
     */
    public java.util.Date getReportDate()
    {
        return this.reportDate;
    }

    /**
     * Set the value of the report_date column.
     * @param reportDate
     */
    public void setReportDate(java.util.Date reportDate)
    {
        this.reportDate = reportDate;
    }

    /**
     * Return the value of the report_name column.
     * @return java.lang.String
     */
    public java.lang.String getReportName()
    {
        return this.reportName;
    }

    /**
     * Set the value of the report_name column.
     * @param reportName
     */
    public void setReportName(java.lang.String reportName)
    {
        this.reportName = reportName;
    }

    /**
     * Return the value of the excute_status column.
     * @return java.lang.String
     */
    public java.lang.String getExcuteStatus()
    {
        return this.excuteStatus;
    }

    /**
     * Set the value of the excute_status column.
     * @param excuteStatus
     */
    public void setExcuteStatus(java.lang.String excuteStatus)
    {
        this.excuteStatus = excuteStatus;
    }

    /**
     * Return the value of the problem column.
     * @return java.lang.String
     */
    public java.lang.String getProblem()
    {
        return this.problem;
    }

    /**
     * Set the value of the problem column.
     * @param problem
     */
    public void setProblem(java.lang.String problem)
    {
        this.problem = problem;
    }

    /**
     * Return the value of the risk column.
     * @return java.lang.String
     */
    public java.lang.String getRisk()
    {
        return this.risk;
    }

    /**
     * Set the value of the risk column.
     * @param risk
     */
    public void setRisk(java.lang.String risk)
    {
        this.risk = risk;
    }

    /**
     * Return the value of the next_plan column.
     * @return java.lang.String
     */
    public java.lang.String getNextPlan()
    {
        return this.nextPlan;
    }

    /**
     * Set the value of the next_plan column.
     * @param nextPlan
     */
    public void setNextPlan(java.lang.String nextPlan)
    {
        this.nextPlan = nextPlan;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof ProjectReports))
            return false;
        ProjectReports that = (ProjectReports) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
