/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:59:44 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the week_reports table. 
 * You can customize the behavior of this class by editing the class, {@link WeekReports()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractWeekReports 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the targets association. */
    private Long targetId;
    
    private Long weekId;

    /** The value of the users association. */
    private Long submitById;

    /** The value of the simple submitDate property. */
    private java.util.Date submitDate;

    /** The value of the simple startDateFact property. */
    private java.util.Date startDateFact;

    /** The value of the simple endDateFact property. */
    private java.util.Date endDateFact;

    /** The value of the simple workloadThisweek property. */
    private java.lang.Integer workloadThisweek;

    /** The value of the simple excuteStatus property. */
    private java.lang.String excuteStatus;

    /** The value of the simple problem property. */
    private java.lang.String problem;

    /**
     * Simple constructor of AbstractWeekReports instances.
     */
    public AbstractWeekReports()
    {
    }

    /**
     * Constructor of AbstractWeekReports instances given a simple primary key.
     * @param id
     */
    public AbstractWeekReports(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    
    
    public Long getSubmitById() {
		return submitById;
	}

	public void setSubmitById(Long submitById) {
		this.submitById = submitById;
	}

	/**
     * Return the value of the submit_date column.
     * @return java.util.Date
     */
    public java.util.Date getSubmitDate()
    {
        return this.submitDate;
    }

    /**
     * Set the value of the submit_date column.
     * @param submitDate
     */
    public void setSubmitDate(java.util.Date submitDate)
    {
        this.submitDate = submitDate;
    }


	public Long getTargetId() {
		return targetId;
	}

	public void setTargetId(Long targetId) {
		this.targetId = targetId;
	}

	public Long getWeekId() {
		return weekId;
	}

	public void setWeekId(Long weekId) {
		this.weekId = weekId;
	}

	/**
     * Return the value of the start_date_fact column.
     * @return java.util.Date
     */
    public java.util.Date getStartDateFact()
    {
        return this.startDateFact;
    }

    /**
     * Set the value of the start_date_fact column.
     * @param startDateFact
     */
    public void setStartDateFact(java.util.Date startDateFact)
    {
        this.startDateFact = startDateFact;
    }

    /**
     * Return the value of the end_date_fact column.
     * @return java.util.Date
     */
    public java.util.Date getEndDateFact()
    {
        return this.endDateFact;
    }

    /**
     * Set the value of the end_date_fact column.
     * @param endDateFact
     */
    public void setEndDateFact(java.util.Date endDateFact)
    {
        this.endDateFact = endDateFact;
    }

    /**
     * Return the value of the workload_thisweek column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getWorkloadThisweek()
    {
        return this.workloadThisweek;
    }

    /**
     * Set the value of the workload_thisweek column.
     * @param workloadThisweek
     */
    public void setWorkloadThisweek(java.lang.Integer workloadThisweek)
    {
        this.workloadThisweek = workloadThisweek;
    }

    /**
     * Return the value of the excute_status column.
     * @return java.lang.String
     */
    public java.lang.String getExcuteStatus()
    {
        return this.excuteStatus;
    }

    /**
     * Set the value of the excute_status column.
     * @param excuteStatus
     */
    public void setExcuteStatus(java.lang.String excuteStatus)
    {
        this.excuteStatus = excuteStatus;
    }

    /**
     * Return the value of the problem column.
     * @return java.lang.String
     */
    public java.lang.String getProblem()
    {
        return this.problem;
    }

    /**
     * Set the value of the problem column.
     * @param problem
     */
    public void setProblem(java.lang.String problem)
    {
        this.problem = problem;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof WeekReports))
            return false;
        WeekReports that = (WeekReports) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
