/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:58:19 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the permissions table. 
 * You can customize the behavior of this class by editing the class, {@link Permissions()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractPermissions 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;
    
    private java.lang.Long parentId;

    /** The value of the simple permissionName property. */
    private java.lang.String permissionName;

    /** The value of the simple permissionUrl property. */
    private java.lang.String permissionUrl;

    /** The value of the simple permissionOrder property. */
    private java.lang.Integer permissionOrder;

    /** The value of the simple isMenu property. */
    private java.lang.Integer permissionLevel;

    /** The value of the simple imageName property. */
    private java.lang.String imageName;

    /**
     * Simple constructor of AbstractPermissions instances.
     */
    public AbstractPermissions()
    {
    }

    /**
     * Constructor of AbstractPermissions instances given a simple primary key.
     * @param id
     */
    public AbstractPermissions(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the permission_name column.
     * @return java.lang.String
     */
    public java.lang.String getPermissionName()
    {
        return this.permissionName;
    }

    /**
     * Set the value of the permission_name column.
     * @param permissionName
     */
    public void setPermissionName(java.lang.String permissionName)
    {
        this.permissionName = permissionName;
    }

    /**
     * Return the value of the permission_url column.
     * @return java.lang.String
     */
    public java.lang.String getPermissionUrl()
    {
        return this.permissionUrl;
    }

    /**
     * Set the value of the permission_url column.
     * @param permissionUrl
     */
    public void setPermissionUrl(java.lang.String permissionUrl)
    {
        this.permissionUrl = permissionUrl;
    }

    /**
     * Return the value of the permission_order column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getPermissionOrder()
    {
        return this.permissionOrder;
    }

    /**
     * Set the value of the permission_order column.
     * @param permissionOrder
     */
    public void setPermissionOrder(java.lang.Integer permissionOrder)
    {
        this.permissionOrder = permissionOrder;
    }

    
    /**
     * Return the value of the image_name column.
     * @return java.lang.String
     */
    public java.lang.String getImageName()
    {
        return this.imageName;
    }

    /**
     * Set the value of the image_name column.
     * @param imageName
     */
    public void setImageName(java.lang.String imageName)
    {
        this.imageName = imageName;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Permissions))
            return false;
        Permissions that = (Permissions) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public java.lang.Long getParentId() {
		return parentId;
	}

	public void setParentId(java.lang.Long parentId) {
		this.parentId = parentId;
	}

	public java.lang.Integer getPermissionLevel() {
		return permissionLevel;
	}

	public void setPermissionLevel(java.lang.Integer permissionLevel) {
		this.permissionLevel = permissionLevel;
	}
}
