/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:58:44 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the products table. 
 * You can customize the behavior of this class by editing the class, {@link Products()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractProducts 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the targets association. */
    private Targets targets;

    /** The value of the users association. */
    private Long referById;

    /** The value of the users1 association. */
    private Long auditById;

    /** The value of the simple productName property. */
    private java.lang.String productName;

    /** The value of the simple productSizePlan property. */
    private java.lang.Integer productSizePlan;

    /** The value of the simple productSizeFact property. */
    private java.lang.Integer productSizeFact;

    /** The value of the simple productUnit property. */
    private java.lang.String productUnit;

    /** The value of the simple referDate property. */
    private java.util.Date referDate;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple auditDate property. */
    private java.util.Date auditDate;

    /** The value of the simple auditRemark property. */
    private java.lang.String auditRemark;

    /**
     * Simple constructor of AbstractProducts instances.
     */
    public AbstractProducts()
    {
    }

    /**
     * Constructor of AbstractProducts instances given a simple primary key.
     * @param id
     */
    public AbstractProducts(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }

    /**
     * Return the value of the target_id column.
     * @return Targets
     */
    public Targets getTargets()
    {
        return this.targets;
    }

    /**
     * Set the value of the target_id column.
     * @param targets
     */
    public void setTargets(Targets targets)
    {
        this.targets = targets;
    }

    /**
     * Return the value of the product_name column.
     * @return java.lang.String
     */
    public java.lang.String getProductName()
    {
        return this.productName;
    }

    /**
     * Set the value of the product_name column.
     * @param productName
     */
    public void setProductName(java.lang.String productName)
    {
        this.productName = productName;
    }

    /**
     * Return the value of the product_size_plan column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getProductSizePlan()
    {
        return this.productSizePlan;
    }

    /**
     * Set the value of the product_size_plan column.
     * @param productSizePlan
     */
    public void setProductSizePlan(java.lang.Integer productSizePlan)
    {
        this.productSizePlan = productSizePlan;
    }

    /**
     * Return the value of the product_size_fact column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getProductSizeFact()
    {
        return this.productSizeFact;
    }

    /**
     * Set the value of the product_size_fact column.
     * @param productSizeFact
     */
    public void setProductSizeFact(java.lang.Integer productSizeFact)
    {
        this.productSizeFact = productSizeFact;
    }

    /**
     * Return the value of the product_unit column.
     * @return java.lang.String
     */
    public java.lang.String getProductUnit()
    {
        return this.productUnit;
    }

    /**
     * Set the value of the product_unit column.
     * @param productUnit
     */
    public void setProductUnit(java.lang.String productUnit)
    {
        this.productUnit = productUnit;
    }

    
    /**
     * Return the value of the refer_date column.
     * @return java.util.Date
     */
    public java.util.Date getReferDate()
    {
        return this.referDate;
    }

    /**
     * Set the value of the refer_date column.
     * @param referDate
     */
    public void setReferDate(java.util.Date referDate)
    {
        this.referDate = referDate;
    }

    /**
     * Return the value of the status column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the status column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

   
    public Long getAuditById() {
		return auditById;
	}

	public void setAuditById(Long auditById) {
		this.auditById = auditById;
	}

	public Long getReferById() {
		return referById;
	}

	public void setReferById(Long referById) {
		this.referById = referById;
	}

	/**
     * Return the value of the audit_date column.
     * @return java.util.Date
     */
    public java.util.Date getAuditDate()
    {
        return this.auditDate;
    }

    /**
     * Set the value of the audit_date column.
     * @param auditDate
     */
    public void setAuditDate(java.util.Date auditDate)
    {
        this.auditDate = auditDate;
    }

    /**
     * Return the value of the audit_remark column.
     * @return java.lang.String
     */
    public java.lang.String getAuditRemark()
    {
        return this.auditRemark;
    }

    /**
     * Set the value of the audit_remark column.
     * @param auditRemark
     */
    public void setAuditRemark(java.lang.String auditRemark)
    {
        this.auditRemark = auditRemark;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Products))
            return false;
        Products that = (Products) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
