/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 27 23:59:23 CST 2006 by MyEclipse Hibernate Tool.
 */
package edu.pm.vo;

import java.io.Serializable;

/**
 * A class that represents a row in the targets table. 
 * You can customize the behavior of this class by editing the class, {@link Targets()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractTargets 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Long id;

    /** The value of the projects association. */
    private Long projectId;

    /** The value of the users association. */
    private Long userSEId;

    /** The value of the users1 association. */
    private Long userPLId;

    /** The value of the targets association. */
    private Long parentId;

    /** The value of the simple isParent property. */
    private java.lang.String isParent;

    /** The value of the simple targetName property. */
    private java.lang.String targetName;

    /** The value of the simple remark property. */
    private java.lang.String remark;

    /** The value of the simple isMilestone property. */
    private java.lang.String isMilestone;

    /** The value of the simple startDatePlan property. */
    private java.util.Date startDatePlan;

    /** The value of the simple endDatePlan property. */
    private java.util.Date endDatePlan;

    /** The value of the simple startDateFact property. */
    private java.util.Date startDateFact;

    /** The value of the simple endDateFact property. */
    private java.util.Date endDateFact;

    /** The value of the simple workloadFact property. */
    private java.lang.Integer workloadFact;

    /** The value of the simple workloadPlan property. */
    private java.lang.Integer workloadPlan;

    /** The value of the simple displayColor property. */
    private java.lang.String displayColor;

    /** The value of the simple status property. */
    private java.lang.String status;

    /** The value of the simple excuteStatus property. */
    private java.lang.String excuteStatus;

    /** The value of the simple isDeleted property. */
    private java.lang.String isDeleted;
    
    private java.lang.Integer targetLevel;
    
    private java.lang.String targetOrder;


    /**
     * Simple constructor of AbstractTargets instances.
     */
    public AbstractTargets()
    {
    }

    /**
     * Constructor of AbstractTargets instances given a simple primary key.
     * @param id
     */
    public AbstractTargets(java.lang.Long id)
    {
        this.setId(id);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Long
     */
    public java.lang.Long getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Long id)
    {
        this.hashValue = 0;
        this.id = id;
    }


    /**
     * Return the value of the is_parent column.
     * @return java.lang.String
     */
    public java.lang.String getIsParent()
    {
        return this.isParent;
    }

    /**
     * Set the value of the is_parent column.
     * @param isParent
     */
    public void setIsParent(java.lang.String isParent)
    {
        this.isParent = isParent;
    }


    /**
     * Return the value of the target_name column.
     * @return java.lang.String
     */
    public java.lang.String getTargetName()
    {
        return this.targetName;
    }

    /**
     * Set the value of the target_name column.
     * @param targetName
     */
    public void setTargetName(java.lang.String targetName)
    {
        this.targetName = targetName;
    }

    /**
     * Return the value of the remark column.
     * @return java.lang.String
     */
    public java.lang.String getRemark()
    {
        return this.remark;
    }

    /**
     * Set the value of the remark column.
     * @param remark
     */
    public void setRemark(java.lang.String remark)
    {
        this.remark = remark;
    }

    /**
     * Return the value of the is_milestone column.
     * @return java.lang.String
     */
    public java.lang.String getIsMilestone()
    {
        return this.isMilestone;
    }

    /**
     * Set the value of the is_milestone column.
     * @param isMilestone
     */
    public void setIsMilestone(java.lang.String isMilestone)
    {
        this.isMilestone = isMilestone;
    }

    /**
     * Return the value of the start_date_plan column.
     * @return java.util.Date
     */
    public java.util.Date getStartDatePlan()
    {
        return this.startDatePlan;
    }

    /**
     * Set the value of the start_date_plan column.
     * @param startDatePlan
     */
    public void setStartDatePlan(java.util.Date startDatePlan)
    {
        this.startDatePlan = startDatePlan;
    }

    /**
     * Return the value of the end_date_plan column.
     * @return java.util.Date
     */
    public java.util.Date getEndDatePlan()
    {
        return this.endDatePlan;
    }

    /**
     * Set the value of the end_date_plan column.
     * @param endDatePlan
     */
    public void setEndDatePlan(java.util.Date endDatePlan)
    {
        this.endDatePlan = endDatePlan;
    }

    /**
     * Return the value of the start_date_fact column.
     * @return java.util.Date
     */
    public java.util.Date getStartDateFact()
    {
        return this.startDateFact;
    }

    /**
     * Set the value of the start_date_fact column.
     * @param startDateFact
     */
    public void setStartDateFact(java.util.Date startDateFact)
    {
        this.startDateFact = startDateFact;
    }

    /**
     * Return the value of the end_date_fact column.
     * @return java.util.Date
     */
    public java.util.Date getEndDateFact()
    {
        return this.endDateFact;
    }

    /**
     * Set the value of the end_date_fact column.
     * @param endDateFact
     */
    public void setEndDateFact(java.util.Date endDateFact)
    {
        this.endDateFact = endDateFact;
    }

    /**
     * Return the value of the workload_fact column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getWorkloadFact()
    {
        return this.workloadFact;
    }

    /**
     * Set the value of the workload_fact column.
     * @param workloadFact
     */
    public void setWorkloadFact(java.lang.Integer workloadFact)
    {
        this.workloadFact = workloadFact;
    }

    /**
     * Return the value of the workload_plan column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getWorkloadPlan()
    {
        return this.workloadPlan;
    }

    /**
     * Set the value of the workload_plan column.
     * @param workloadPlan
     */
    public void setWorkloadPlan(java.lang.Integer workloadPlan)
    {
        this.workloadPlan = workloadPlan;
    }

    /**
     * Return the value of the display_color column.
     * @return java.lang.String
     */
    public java.lang.String getDisplayColor()
    {
        return this.displayColor;
    }

    /**
     * Set the value of the display_color column.
     * @param displayColor
     */
    public void setDisplayColor(java.lang.String displayColor)
    {
        this.displayColor = displayColor;
    }

    /**
     * Return the value of the status column.
     * @return java.lang.String
     */
    public java.lang.String getStatus()
    {
        return this.status;
    }

    /**
     * Set the value of the status column.
     * @param status
     */
    public void setStatus(java.lang.String status)
    {
        this.status = status;
    }

    /**
     * Return the value of the excute_status column.
     * @return java.lang.String
     */
    public java.lang.String getExcuteStatus()
    {
        return this.excuteStatus;
    }

    /**
     * Set the value of the excute_status column.
     * @param excuteStatus
     */
    public void setExcuteStatus(java.lang.String excuteStatus)
    {
        this.excuteStatus = excuteStatus;
    }

    /**
     * Return the value of the is_deleted column.
     * @return java.lang.String
     */
    public java.lang.String getIsDeleted()
    {
        return this.isDeleted;
    }

    /**
     * Set the value of the is_deleted column.
     * @param isDeleted
     */
    public void setIsDeleted(java.lang.String isDeleted)
    {
        this.isDeleted = isDeleted;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof Targets))
            return false;
        Targets that = (Targets) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int idValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + idValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }

	public Long getProjectId() {
		return projectId;
	}

	public void setProjectId(Long projectId) {
		this.projectId = projectId;
	}

	
	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	public Long getUserPLId() {
		return userPLId;
	}

	public void setUserPLId(Long userPLId) {
		this.userPLId = userPLId;
	}

	public Long getUserSEId() {
		return userSEId;
	}

	public void setUserSEId(Long userSEId) {
		this.userSEId = userSEId;
	}

	public java.lang.Integer getTargetLevel() {
		return targetLevel;
	}

	public void setTargetLevel(java.lang.Integer targetLevel) {
		this.targetLevel = targetLevel;
	}

	public java.lang.String getTargetOrder() {
		return targetOrder;
	}

	public void setTargetOrder(java.lang.String targetOrder) {
		this.targetOrder = targetOrder;
	}

}
